"use client";
import { useEffect, useRef, useState } from 'react';
import { RelaxAudio } from '@/lib/relax-audio';
export default function Decompress(){const [mode,setMode]=useState('气泡纸'),[sound,setSound]=useState(false),[notice,setNotice]=useState(''),[popped,setPopped]=useState<number[]>([]),[switches,setSwitches]=useState<number[]>([]),[ripples,setRipples]=useState<{id:number;x:number;y:number}[]>([]);const audio=useRef<RelaxAudio|null>(null),serial=useRef(0),drag=useRef(false),last=useRef(-1),timers=useRef<ReturnType<typeof setTimeout>[]>([]),intent=useRef(0);
 useEffect(()=>{const hidden=()=>{if(document.hidden){intent.current++;audio.current?.stop();setSound(false)}};document.addEventListener('visibilitychange',hidden);return()=>{intent.current++;audio.current?.stop();timers.current.forEach(clearTimeout);document.removeEventListener('visibilitychange',hidden)}},[]);
 async function toggle(){if(sound){intent.current++;audio.current?.stop();setSound(false);return;}const request=++intent.current;try{audio.current??=new RelaxAudio();await audio.current.enableEffects(.5);if(request!==intent.current)return;setSound(true);setNotice('音效已开启，切到工作视图或后台时自动关闭。')}catch{setNotice('浏览器未允许声音，请稍后重试')}}
 function flip(i:number){if(last.current===i&&drag.current)return;last.current=i;setSwitches(v=>v.includes(i)?v.filter(x=>x!==i):[...v,i]);if(sound)audio.current?.effect('click');}
 return <section className="bubble-panel"><div className="break-heading"><div><small>随手解压，不计分</small><h2>把紧绷，轻轻松开</h2></div><button className="relax-sound" aria-pressed={sound} onClick={toggle}>{sound?'关闭音效':'开启音效'}</button></div><div className="relax-tabs">{['气泡纸','拨片板','静水池'].map(m=><button key={m} className={mode===m?'active':''} onClick={()=>setMode(m)}>{m}</button>)}</div>
 {mode==='气泡纸'&&<><div className="bubbles">{Array.from({length:35},(_,i)=><button key={i} disabled={popped.includes(i)} className={popped.includes(i)?'popped':''} aria-label={`第${i+1}个气泡${popped.includes(i)?'已捏破':''}`} onClick={()=>{setPopped(v=>[...v,i]);if(sound)audio.current?.effect('pop')}}><span/></button>)}</div><div className="bubble-footer"><p>{popped.length} / 35 · 捏完可以再来一张。</p><button onClick={()=>setPopped([])}>换张新的</button></div></>}
 {mode==='拨片板'&&<><div className="toggle-board" onPointerMove={e=>{if(!drag.current)return;const hit=document.elementFromPoint(e.clientX,e.clientY)?.closest<HTMLButtonElement>("button[data-flip]");if(hit)flip(Number(hit.dataset.flip))}} onPointerUp={()=>{drag.current=false;last.current=-1}} onPointerLeave={()=>{drag.current=false;last.current=-1}} onPointerCancel={()=>{drag.current=false;last.current=-1}}>{Array.from({length:24},(_,i)=><button data-flip={i} aria-label={`第${i+1}块拨片`} aria-pressed={switches.includes(i)} className={switches.includes(i)?'flipped':''} key={i} onPointerDown={e=>{e.preventDefault();last.current=-1;flip(i);drag.current=true;}} onPointerEnter={()=>{if(drag.current)flip(i)}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();drag.current=false;flip(i)}}}><i/></button>)}</div><div className="bubble-footer"><p>点击或按住划过，听一声轻轻的咔哒。</p><button onClick={()=>setSwitches([])}>全部归位</button></div></>}
 {mode==='静水池'&&<><div className="water-pool" role="button" tabIndex={0} aria-label="点击水面产生涟漪" onClick={e=>{const r=e.currentTarget.getBoundingClientRect(),id=serial.current++;setRipples(v=>[...v.slice(-19),{id,x:(e.clientX-r.left)/r.width*100,y:(e.clientY-r.top)/r.height*100}]);if(sound)audio.current?.effect('water');timers.current.push(setTimeout(()=>setRipples(v=>v.filter(x=>x.id!==id)),2400))}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();const id=serial.current++;setRipples(v=>[...v.slice(-19),{id,x:50,y:50}]);if(sound)audio.current?.effect('water');timers.current.push(setTimeout(()=>setRipples(v=>v.filter(x=>x.id!==id)),2400))}}}>{ripples.map(r=><i key={r.id} style={{left:r.x+'%',top:r.y+'%'}}/>)}<span>点一下，等涟漪慢慢散开。</span></div><div className="bubble-footer"><p>什么都不用收集，水面会自己平静。</p><button onClick={()=>setRipples([])}>抚平水面</button></div></>}
 <p className="sound-notice" role="status">{notice||'音效默认关闭；打开后，气泡、拨片和水波各有不同声音。'}</p></section>}
