"use client";
import { useEffect, useRef, useState } from 'react';
import { courierStep, Dir, dirs, newBalance, newBento, newCourier, newTwins, moveTwins, balanceTotals, latinSolved, StudioKind, TwinState } from '@/lib/studio-puzzles';
import { recordBest, useBest } from '@/lib/local-preferences';
import './studio-games.css';
const levels=['入门','进阶','高手'];
const info:Record<StudioKind,{name:string;sub:string;rule:string;tip:string}>= {
 twins:{name:'双星归位',sub:'一个方向，两份默契',rule:'每次按方向，两颗星都会走一格。碰到墙或边界的星会停下，另一颗继续走；两颗星不能重叠或交换位置。把粉星和蓝星分别送到同色星窝。',tip:'有时，让一颗星贴着墙停一下，另一颗就能追上节奏。'},
 courier:{name:'云朵邮差',sub:'一条小路，收齐好心情',rule:'从邮局出发，走相邻的云格，收集全部信件，再抵达终点。同一格只能走一次，步数不能超过本局额度；走错可以退回。',tip:'信件可以按任意顺序收集。先想终点前的最后一封信，再倒着规划。'},
 balance:{name:'天平茶室',sub:'不多不少，刚刚好',rule:'选择左盘或右盘，再点一个茶点放上去；点已放好的茶点可拿回。把全部茶点分到两侧，总重量完全相等就完成。数字就是每份茶点的重量。',tip:'相同的重量可以互相抵消。先算总重量的一半，就是每边的目标。'},
 bento:{name:'便当分格',sub:'让每一口，都有自己的位置',rule:'点击空格，再选一种食物。每行、每列都要放齐所有种类，并且不能重复。固定的食物不能改动。没有九宫格额外规则。',tip:'先看一行或一列只缺什么。每局经过求解器验证，只有一个答案。'}
};
const foods=['饭团','番茄','玉米','青菜','蓝莓'],foodSymbols=['🍙','🍅','🌽','🥬','🫐'];
export default function StudioGames({kind}:{kind:StudioKind}){
 const [level,setLevel]=useState(0),[seed,setSeed]=useState(8517),[steps,setSteps]=useState(0),[assisted,setAssisted]=useState(false),[notice,setNotice]=useState(''),[share,setShare]=useState('');
 const [twins,setTwins]=useState(()=>newTwins(8517,0)),[stars,setStars]=useState<TwinState>(()=>newTwins(8517,0).start),[starHistory,setStarHistory]=useState<TwinState[]>([]);
 const [courier,setCourier]=useState(()=>newCourier(8517,0)),[path,setPath]=useState<number[]>([0]);
 const [balance,setBalance]=useState(()=>newBalance(8517,0)),[slots,setSlots]=useState<number[]>([0,0,0,0]),[side,setSide]=useState(1);
 const [bento,setBento]=useState(()=>newBento(8517,0)),[meal,setMeal]=useState(()=>newBento(8517,0).board),[selected,setSelected]=useState<number|null>(null);
 const recorded=useRef(false),scope=useRef<HTMLDivElement>(null),best=useBest(kind+':'+levels[level]),totals=balanceTotals(balance.weights,slots);
 const won=kind==='twins'?stars.every((n,i)=>n===twins.goal[i]):kind==='courier'?path.at(-1)===courier.goal&&courier.stamps.every(n=>path.includes(n)):kind==='balance'?slots.every(Boolean)&&totals.left===totals.right:latinSolved(meal,bento.size);
 function reset(d=level,s=Math.floor(Math.random()*999999)){const t=newTwins(s,d),c=newCourier(s,d),b=newBalance(s,d),l=newBento(s,d);setTwins(t);setStars(t.start);setStarHistory([]);setCourier(c);setPath([c.start]);setBalance(b);setSlots(b.weights.map(()=>0));setBento(l);setMeal(l.board);setSelected(null);setLevel(d);setSeed(s);setSteps(0);setAssisted(false);setNotice('');setShare('');recorded.current=false;}
 useEffect(()=>{if(won&&!recorded.current){recorded.current=true;if(!assisted)recordBest(kind+':'+levels[level],steps)}},[won,assisted,steps,kind,level]);
 function move(d:Dir){if(won)return;const next=moveTwins(stars,d,twins.walls,twins.size);if(next===stars){setNotice('这个方向两颗星都无法前进，换个方向试试。');return;}setStarHistory(h=>[...h,stars]);setStars(next);setSteps(n=>n+1);setNotice('');}
 function cell(id:number){if(won)return;const next=courierStep(path,id,courier);if(next.error)setNotice(next.error);else{setPath(next.path);setSteps(n=>n+1);setNotice('')}}
 function hint(){setAssisted(true);if(kind==='twins'){setStars(twins.start);setStarHistory([]);setNotice(`已回到起点。参考路线：${twins.solution.map(d=>({up:'↑',right:'→',down:'↓',left:'←'}[d])).join(' ')}`)}else if(kind==='courier'){setPath([courier.start]);setNotice(`已回到起点。参考路径格号：${courier.solution.map(n=>n+1).join(' → ')}`)}else if(kind==='balance')setNotice(`左盘放第 ${balance.solution.flatMap((s,i)=>s===1?[i+1]:[]).join('、')} 份，其余放右盘。`);else{const id=meal.findIndex((n,i)=>n!==bento.solution[i]);if(id>=0){setMeal(b=>b.map((n,i)=>i===id?bento.solution[i]:n));setSelected(id);setSteps(n=>n+1);setNotice(`已帮你填好第 ${id+1} 格。`)}}}
 async function copy(){const text=`【歇一会儿 · ${info[kind].name}】${levels[level]}\n${steps} 步通关${assisted?'（辅助局）':''}\n${location.origin}/?play=${kind}`;try{await navigator.clipboard.writeText(text);setShare('通关成绩与游戏链接已复制')}catch{setShare(text)}}
 const conflict=(i:number)=>meal[i]&&meal.some((n,j)=>j!==i&&n===meal[i]&&(Math.floor(j/bento.size)===Math.floor(i/bento.size)||j%bento.size===i%bento.size));
 return <section className="studio-layout"><div className="studio-panel"><header><div><small>{info[kind].sub}</small><h2>{info[kind].name}</h2></div><span>{steps} 步</span></header><div className="difficulty-bar">{levels.map((d,i)=><button key={d} aria-pressed={level===i} className={level===i?'active':''} onClick={()=>{if(level!==i)reset(i)}}>{d}</button>)}<small>切换难度会重开本局</small></div><p className="studio-rule">{info[kind].rule}</p>
 {kind==='twins'&&<div ref={scope} tabIndex={0} className="twins-area" aria-label="双星棋盘，方向键或下方按钮移动" onKeyDown={e=>{const map:Record<string,Dir>={ArrowUp:'up',ArrowRight:'right',ArrowDown:'down',ArrowLeft:'left'};if(map[e.key]){e.preventDefault();move(map[e.key])}}}><div className="studio-grid twins-grid">{Array.from({length:25},(_,i)=><div key={i} className={`twin-cell ${twins.walls.includes(i)?'wall':''}`} aria-label={twins.walls.includes(i)?'墙':`第${i+1}格`}>{twins.goal.map((n,j)=>n===i?<span key={j} className={'star-home star-'+j}>⌂</span>:null)}{stars.map((n,j)=>n===i?<span key={j} className={'star-piece star-'+j}>✦</span>:null)}</div>)}</div><div className="twin-legend"><span>粉星 → 粉窝</span><span>蓝星 → 蓝窝</span></div><div className="direction-pad">{dirs.map(d=><button disabled={won} key={d} aria-label={{up:'向上',right:'向右',down:'向下',left:'向左'}[d]} onClick={()=>{move(d);scope.current?.focus({preventScroll:true})}}>{{up:'↑',right:'→',down:'↓',left:'←'}[d]}</button>)}</div><button className="studio-undo" disabled={won||!starHistory.length} onClick={()=>{setStars(starHistory.at(-1)!);setStarHistory(v=>v.slice(0,-1));setAssisted(true);setNotice('已退一步，本局计为辅助局。')}}>退一步</button></div>}
 {kind==='courier'&&<><div className="courier-stats"><span>信件 {courier.stamps.filter(n=>path.includes(n)).length} / {courier.stamps.length}</span><span>路程 {path.length-1} / {courier.budget} 格</span></div><div className="studio-grid courier-grid" style={{gridTemplateColumns:`repeat(${courier.size},1fr)`}}>{Array.from({length:courier.size**2},(_,i)=><button key={i} disabled={won||courier.walls.includes(i)} className={`${courier.walls.includes(i)?'wall':''} ${path.includes(i)?'visited':''} ${path.at(-1)===i?'postman':''}`} aria-label={`第${i+1}格${i===courier.goal?'终点':courier.stamps.includes(i)?'信件':courier.walls.includes(i)?'障碍':'云路'}`} onClick={()=>cell(i)}><small>{i+1}</small><b>{courier.walls.includes(i)?'☁':path.at(-1)===i?'✉':i===courier.goal?'⚑':courier.stamps.includes(i)?path.includes(i)?'✓':'✉':path.includes(i)?'·':''}</b></button>)}</div><button className="studio-undo" disabled={won||path.length<2} onClick={()=>{setPath(v=>v.slice(0,-1));setAssisted(true);setNotice('退回一步，试试另一条路。')}}>退回上一格</button></>}
 {kind==='balance'&&<><div className="scale-scene"><div className="scale-beam" style={{transform:`rotate(${Math.max(-12,Math.min(12,(totals.right-totals.left)*2))}deg)`}}/><i className="scale-pivot"/><button disabled={won} className={`scale-pan left ${side===1?'active':''}`} onClick={()=>setSide(1)}>左盘<b>{totals.left}</b></button><button disabled={won} className={`scale-pan right ${side===2?'active':''}`} onClick={()=>setSide(2)}>右盘<b>{totals.right}</b></button></div><p className="scale-target">全部茶点共 {balance.weights.reduce((a,b)=>a+b,0)} 份重量，每边需要一半。当前选择：{side===1?'左盘':'右盘'}</p><div className="tea-tray">{balance.weights.map((w,i)=><button disabled={won} key={i} className={slots[i]?'placed':''} onClick={()=>{setSlots(v=>v.map((n,j)=>i===j?n?0:side:n));setSteps(n=>n+1)}}><small>第{i+1}份</small><span>{['🍡','🍰','🥮','🍪'][i%4]}</span><b>{w}</b><i>{slots[i]===1?'在左盘':slots[i]===2?'在右盘':'待摆放'}</i></button>)}</div></>}
 {kind==='bento'&&<><div className="studio-grid bento-grid" style={{gridTemplateColumns:`repeat(${bento.size},1fr)`}}>{meal.map((n,i)=><button key={i} disabled={!!bento.board[i]||won} aria-label={`第${i+1}格${n?foods[n-1]:'空格'}${bento.board[i]?' 固定':''}`} className={`${bento.board[i]?'fixed':''} ${selected===i?'selected':''} ${conflict(i)?'conflict':''}`} onClick={()=>setSelected(i)}>{n?foodSymbols[n-1]:'＋'}{bento.board[i]>0&&<small>固定</small>}</button>)}</div><div className="food-palette">{foodSymbols.slice(0,bento.size).map((f,i)=><button key={f} disabled={won||selected===null||!!bento.board[selected]} onClick={()=>{setMeal(b=>b.map((n,j)=>j===selected?i+1:n));setSteps(n=>n+1)}}>{f}<small>{foods[i]}</small></button>)}<button disabled={won||selected===null||!!bento.board[selected]} onClick={()=>setMeal(b=>b.map((n,j)=>j===selected?0:n))}>清空</button></div><p className="studio-muted">边框变红表示该行或该列重复；固定格不能修改。</p></>}
 <div className={`studio-feedback ${won?'won':''}`} role="status">{won?`完成啦！${steps} 步${assisted?' · 辅助局不计最佳':' · 已记录本档最佳成绩'}。`:notice||'慢慢想，没有倒计时，也没有失败惩罚。'}</div><div className="mini-actions"><button onClick={()=>reset()}>换一局</button><button onClick={()=>reset(level,seed)}>重玩本局</button><button disabled={won} onClick={hint}>{kind==='bento'?'帮填一格':'看看提示'}</button><button disabled={!won} onClick={copy}>分享成绩</button></div>{share&&<p className="mini-copy" role="status">{share}</p>}</div><aside className="studio-aside"><h3>{levels[level]}，不同在哪里？</h3><p>{kind==='twins'?`最短参考路径为 ${[4,7,10][level]} 步，墙块 ${5+level} 块，双星的相对位置需要更多次调整。`:kind==='courier'?`${courier.size} × ${courier.size} 地图，${level+2} 封信件，路程上限 ${courier.budget} 步。`:kind==='balance'?`${balance.weights.length} 份茶点，数量越多，配重组合越复杂。`:`${bento.size} × ${bento.size} 餐盒，${bento.size} 种食物，${bento.board.filter(n=>!n).length} 个空格。`}</p><h3>小秘诀</h3><p>{info[kind].tip}</p><h3>这一档的最佳</h3><b>{best===null?'等你来开张':`${best} 步`}</b><p>使用提示或撤回会标记辅助局，不刷新最佳。仅保存在当前浏览器。</p><small>本站独立实现规则与关卡生成，无外部游戏嵌入。</small></aside></section>;
}
