export type Difficulty = '入门' | '进阶' | '高手';
export const difficulties: Difficulty[] = ['入门', '进阶', '高手'];
export function rng(seed: number) { let a = seed >>> 0; return () => { a += 0x6D2B79F5; let t = a; t = Math.imul(t ^ t >>> 15, t | 1); t ^= t + Math.imul(t ^ t >>> 7, t | 61); return ((t ^ t >>> 14) >>> 0) / 4294967296; }; }
export function shuffle<T>(items: T[], random = Math.random): T[] { const arr = [...items]; for (let i = arr.length - 1; i > 0; i--) { const j = Math.floor(random() * (i + 1)); [arr[i], arr[j]] = [arr[j], arr[i]]; } return arr; }
export const SIZE = 9;
export const CENTER = 40;
export function edge(id: number) { const r = Math.floor(id / SIZE), c = id % SIZE; return r === 0 || r === SIZE - 1 || c === 0 || c === SIZE - 1; }
export function neighbors(id: number): number[] { const r = Math.floor(id / SIZE), c = id % SIZE, d = r % 2 ? 1 : -1; return [[r,c-1],[r,c+1],[r-1,c],[r-1,c+d],[r+1,c],[r+1,c+d]].filter(([y,x]) => x >= 0 && x < SIZE && y >= 0 && y < SIZE).map(([y,x]) => y * SIZE + x); }
export function escapePath(start: number, blocked: number[]): number[] | null { const walls = new Set(blocked); if (walls.has(start)) return null; const queue = [start], prev = new Map<number, number>(); prev.set(start, -1); for(let i = 0; i < queue.length; i++) { const id = queue[i]; if(edge(id)) { const path = []; for(let x = id; x !== -1; x = prev.get(x)!) path.unshift(x); return path; } for(const n of neighbors(id)) if(!walls.has(n) && !prev.has(n)) { prev.set(n,id); queue.push(n); } } return null; }
export type TrapState = { walls: number[]; actor: number; moves: number; status: 'playing'|'win'|'lose' };
export function newTrap(seed: number, difficulty: Difficulty): TrapState { const random = rng(seed), count = [20,13,7][difficulties.indexOf(difficulty)]; let walls: number[] = []; for(let n=0;n<80;n++) { walls = shuffle(Array.from({length:81},(_,i)=>i).filter(i=>i!==CENTER), random).slice(0,count); if(escapePath(CENTER,walls)) break; } if(!escapePath(CENTER,walls)) walls = []; return {walls, actor:CENTER, moves:0, status:'playing'}; }
export function trapTurn(state: TrapState, cell: number): TrapState { if(state.status !== 'playing' || cell < 0 || cell >= 81 || state.walls.includes(cell) || cell === state.actor) return state; const walls=[...state.walls,cell], path=escapePath(state.actor,walls), moves=state.moves+1; if(!path) return {...state,walls,moves,status:'win'}; const actor=path[1] ?? path[0]; return {walls,actor,moves,status:edge(actor)?'lose':'playing'}; }
export function flipLights(board: boolean[], id: number, size: number): boolean[] { const r=Math.floor(id/size),c=id%size, ids = [[r,c],[r-1,c],[r+1,c],[r,c-1],[r,c+1]].filter(([y,x])=>x>=0&&x<size&&y>=0&&y<size).map(([y,x])=>y*size+x); return board.map((on,i)=>ids.includes(i)?!on:on); }
export function newLights(seed: number, difficulty: Difficulty) { const level=difficulties.indexOf(difficulty), size=level===2?5:4; let board=Array<boolean>(size*size).fill(true); const solution=shuffle(Array.from({length:size*size},(_,i)=>i),rng(seed)).slice(0,[3,7,12][level]); solution.forEach(i=>{board=flipLights(board,i,size)}); if(board.every(Boolean)) { board=flipLights(board,0,size); const index=solution.indexOf(0); if(index>=0) solution.splice(index,1); else solution.push(0); } return {board,solution,size}; }
export const emblems = [ ['剑','独孤九剑'],['掌','降龙十八掌'],['竹','打狗棒法'],['阳','九阳神功'],['阴','九阴真经'],['步','凌波微步'],['指','六脉神剑'],['移','乾坤大挪移'],['拳','太极拳'],['刀','胡家刀法'] ];
export function newMemory(seed: number, difficulty: Difficulty) { const count=[6,8,10][difficulties.indexOf(difficulty)]; return shuffle(Array.from({length:count*2},(_,i)=>i%count),rng(seed)); }
