// 浏览器内合成的环境与触觉音效，不是实地录音；不依赖外部音频请求。
export class RelaxAudio {
 context:AudioContext|null=null; master:GainNode|null=null; private nodes:AudioNode[]=[]; private sources:(AudioBufferSourceNode|OscillatorNode)[]=[]; private timer:ReturnType<typeof setInterval>|null=null; private generation=0;
 async start(scene:string,volume:number){this.stop();const generation=this.generation;const ac=new AudioContext();this.context=ac;await ac.resume();if(this.generation!==generation){void ac.close().catch(()=>{});return false;}const master=ac.createGain();master.gain.value=volume;master.connect(ac.destination);this.master=master;
 const noise=(seconds:number,filterType:BiquadFilterType,freq:number,amount:number,slow:number)=>{const buf=ac.createBuffer(2,ac.sampleRate*seconds,ac.sampleRate);for(let channel=0;channel<2;channel++){const data=buf.getChannelData(channel);let v=0;for(let i=0;i<data.length;i++){const n=Math.random()*2-1;v=(v+.045*n)/1.045;data[i]=filterType==='lowpass'?v*2.8:n*.28;}}const src=ac.createBufferSource();src.buffer=buf;src.loop=true;const filter=ac.createBiquadFilter();filter.type=filterType;filter.frequency.value=freq;const g=ac.createGain();g.gain.value=amount;const lfo=ac.createOscillator(),lg=ac.createGain();lfo.frequency.value=slow;lg.gain.value=amount*.35;lfo.connect(lg);lg.connect(g.gain);src.connect(filter);filter.connect(g);g.connect(master);src.start();lfo.start();this.sources.push(src,lfo);this.nodes.push(filter,g,lg);};
 if(scene==='雨窗'){noise(17,'highpass',1200,.45,.13);noise(23,'lowpass',650,.6,.08);this.timer=setInterval(()=>this.effect('drop',.2),170);}else if(scene==='竹林'){noise(19,'bandpass',1800,.2,.22);noise(29,'lowpass',750,.45,.11);this.timer=setInterval(()=>this.effect('bamboo',.1),1600);}else{noise(31,'lowpass',300,.65,.07);noise(19,'bandpass',620,.12,.12);}return true;
 }
 async enableEffects(volume=.4){if(!this.context){const ac=new AudioContext();this.context=ac;const g=ac.createGain();g.gain.value=volume;g.connect(ac.destination);this.master=g;}await this.context!.resume();}
 setVolume(v:number){if(this.master&&this.context)this.master.gain.setTargetAtTime(v,this.context.currentTime,.12);}
 effect(kind:'pop'|'click'|'water'|'drop'|'bamboo',strength=.6){const ac=this.context,m=this.master;if(!ac||!m||ac.state!=='running')return;const time=ac.currentTime;const osc=ac.createOscillator(),g=ac.createGain(),pan=ac.createStereoPanner();const frequencies={pop:[420,75],click:[850,240],water:[650,170],drop:[1200,700],bamboo:[1500,550]}[kind];osc.type=kind==='click'?'triangle':'sine';osc.frequency.setValueAtTime(frequencies[0]+Math.random()*70,time);osc.frequency.exponentialRampToValueAtTime(frequencies[1],time+.09);g.gain.setValueAtTime(.001,time);g.gain.exponentialRampToValueAtTime(Math.max(.001,strength*.32),time+.004);g.gain.exponentialRampToValueAtTime(.001,time+(kind==='water'?.45:.16));pan.pan.value=(Math.random()-.5)*1.5;osc.connect(g);g.connect(pan);pan.connect(m);osc.start();osc.stop(time+.5);osc.onended=()=>{osc.disconnect();g.disconnect();pan.disconnect()};
 if(kind==='pop'){const buffer=ac.createBuffer(1,ac.sampleRate*.025,ac.sampleRate),d=buffer.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*(1-i/d.length);const src=ac.createBufferSource(),ng=ac.createGain();src.buffer=buffer;ng.gain.value=.2;src.connect(ng);ng.connect(m);src.start();src.onended=()=>{src.disconnect();ng.disconnect()};}
 }
 stop(){this.generation++;if(this.timer)clearInterval(this.timer);this.timer=null;for(const src of this.sources){try{src.stop()}catch{}src.disconnect()}this.sources=[];this.nodes.forEach(n=>n.disconnect());this.nodes=[];if(this.context)void this.context.close().catch(()=>{});this.context=null;this.master=null;}
}
