// 分层程序音景，非实地录音。音量同时调制雨势/风势，和前端场景共用强度。
import { gustAt, clampIntensity } from './scenery';
export class RelaxAudio {
 context:AudioContext|null=null; master:GainNode|null=null;
 private sources:(AudioBufferSourceNode|OscillatorNode)[]=[];private nodes:AudioNode[]=[];private timers:ReturnType<typeof setTimeout>[]=[];private generation=0;private intensity=.25;private ambient=false;
 async start(scene:string,volume:number){this.stop();const gen=this.generation;const ac=new AudioContext();this.context=ac;await ac.resume();if(gen!==this.generation){void ac.close().catch(()=>{});return false;}const master=ac.createGain();master.gain.setValueAtTime(0,ac.currentTime);master.gain.linearRampToValueAtTime(volume*.8,ac.currentTime+.6);const limiter=ac.createDynamicsCompressor();limiter.threshold.value=-18;limiter.ratio.value=5;master.connect(limiter);limiter.connect(ac.destination);this.nodes.push(limiter);this.master=master;this.intensity=volume;this.ambient=true;
 const layer=(type:BiquadFilterType,freq:number,amount:number,drift:number,brown=false)=>{const buffer=ac.createBuffer(2,ac.sampleRate*19,ac.sampleRate);for(let ch=0;ch<2;ch++){const a=buffer.getChannelData(ch);let last=0;for(let i=0;i<a.length;i++){const white=Math.random()*2-1;last=(last+.035*white)/1.035;const envelope=.8+.12*Math.sin(i/ac.sampleRate*.43+ch*2)+.08*Math.sin(i/ac.sampleRate*1.1);a[i]=(brown?last*3.2:white*.28)*envelope;}const fade=Math.floor(ac.sampleRate*.08);for(let i=0;i<fade;i++){a[i]*=i/fade;a[a.length-1-i]*=i/fade;}}
 const src=ac.createBufferSource(),filter=ac.createBiquadFilter(),g=ac.createGain(),lfo=ac.createOscillator(),depth=ac.createGain();src.buffer=buffer;src.loop=true;filter.type=type;filter.frequency.value=freq;filter.Q.value=.45;g.gain.value=amount;lfo.frequency.value=drift;depth.gain.value=amount*.22;lfo.connect(depth);depth.connect(g.gain);src.connect(filter);filter.connect(g);g.connect(master);src.start(0,Math.random()*9);lfo.start();this.sources.push(src,lfo);this.nodes.push(filter,g,depth);};
 // 雨：宽频细雨底 + 窗外低频雨幕 + 不规则近处雨点，无循环的音符式滴声。
 if(scene==='雨窗'){layer('highpass',1300,.9,.17);layer('lowpass',950,1.15,.07,true);layer('bandpass',3800,.28,.31);}
 // 竹林：缓慢风团 + 高频叶片摩擦，木质碰击只偶尔出现。
 else if(scene==='竹林'){layer('lowpass',650,1.35,.09,true);layer('bandpass',2600,.48,.23);layer('highpass',5200,.13,.37);}

 const schedule=()=>{if(gen!==this.generation||this.context?.state==='closed')return;if(this.intensity>0){if(scene==='雨窗')this.burst(1800+Math.random()*3200,.035+Math.random()*.09,.11+Math.random()*.09);else if(scene==='竹林'){this.burst(1600+Math.random()*3000,.25+Math.random()*.5,(.035+this.intensity*.16)*gustAt(ac.currentTime));if(Math.random()<this.intensity*.07)this.effect('bamboo',.045);}}
 const delay=scene==='雨窗'?(100+Math.random()*240)/(1+this.intensity*3):scene==='竹林'?(800+Math.random()*1600)/(1+this.intensity*2):2000;this.timers=[setTimeout(schedule,delay)];};schedule();return true;
 }
 private burst(freq:number,duration:number,amount:number){const ac=this.context,m=this.master;if(!ac||!m||ac.state!=='running')return;const b=ac.createBuffer(1,Math.ceil(ac.sampleRate*duration),ac.sampleRate),a=b.getChannelData(0);for(let i=0;i<a.length;i++){const t=i/a.length;a[i]=(Math.random()*2-1)*Math.sin(Math.PI*t)*Math.exp(-t*4);}const src=ac.createBufferSource(),f=ac.createBiquadFilter(),g=ac.createGain(),pan=ac.createStereoPanner();src.buffer=b;f.type='bandpass';f.frequency.value=freq;f.Q.value=.7;g.gain.value=amount;pan.pan.value=(Math.random()-.5)*1.8;src.connect(f);f.connect(g);g.connect(pan);pan.connect(m);src.start();src.onended=()=>{src.disconnect();f.disconnect();g.disconnect();pan.disconnect()};}
 async enableEffects(volume=.4){if(!this.context){const ac=new AudioContext();this.context=ac;const g=ac.createGain();g.gain.value=volume;g.connect(ac.destination);this.master=g;this.ambient=false;}await this.context!.resume();}
 setVolume(v:number){this.intensity=clampIntensity(v);if(this.master&&this.context)this.master.gain.setTargetAtTime(this.intensity*(this.ambient ? .8 : 1),this.context.currentTime,.2);}
 effect(kind:'pop'|'click'|'water'|'drop'|'bamboo',strength=.6){const ac=this.context,m=this.master;if(!ac||!m||ac.state!=='running')return;const t=ac.currentTime,o=ac.createOscillator(),g=ac.createGain(),p=ac.createStereoPanner();const frequencies={pop:[420,75],click:[850,240],water:[650,170],drop:[1200,700],bamboo:[500,180]}[kind];o.type=kind==='click'||kind==='bamboo'?'triangle':'sine';o.frequency.setValueAtTime(frequencies[0]+Math.random()*50,t);o.frequency.exponentialRampToValueAtTime(frequencies[1],t+.09);g.gain.setValueAtTime(.001,t);g.gain.exponentialRampToValueAtTime(Math.max(.001,strength*.32),t+.004);g.gain.exponentialRampToValueAtTime(.001,t+(kind==='water'?.45:.16));p.pan.value=(Math.random()-.5)*1.5;o.connect(g);g.connect(p);p.connect(m);o.start();o.stop(t+.5);o.onended=()=>{o.disconnect();g.disconnect();p.disconnect()};if(kind==='pop')this.burst(2000,.035,.5);}
 stop(){this.generation++;this.timers.forEach(clearTimeout);this.timers=[];for(const s of this.sources){try{s.stop()}catch{}s.disconnect()}this.sources=[];this.nodes.forEach(n=>n.disconnect());this.nodes=[];if(this.context)void this.context.close().catch(()=>{});this.context=null;this.master=null;}
}
