"use client";
import Link from 'next/link';
import { useEffect, useRef, useState } from 'react';
import { readLocal, writeLocal } from '@/lib/local-preferences';
import VentStation from '@/components/vent-station';
import LocalDataPanel from '@/components/local-data-panel';
import './break.css';
import Decompress from '@/components/decompress';
import OffworkReminder from '@/components/offwork-reminder';
import { RelaxAudio } from '@/lib/relax-audio';
import AmbientWindow from '@/components/ambient-window';
import { sceneDynamics } from '@/lib/scenery';
type Scene='雨窗'|'竹林';
const initialRows=[['需求整理','待确认','周一','补充使用场景'],['页面评审','进行中','周三','核对交互细节'],['联调检查','未开始','周五','记录问题清单'],['周报归档','未开始','周五','整理本周进展']];
export default function BreakPage(){
 const skipWorkPersist=useRef(false);
 const [work,setWork]=useState(false),[scene,setScene]=useState<Scene>('雨窗'),[sound,setSound]=useState(false),[volume,setVolume]=useState(.25),[notice,setNotice]=useState(''),[loaded,setLoaded]=useState(false);
 const [target,setTarget]=useState('18:00'),[draft,setDraft]=useState('18:00'),[now,setNow]=useState<Date|null>(null),[rows,setRows]=useState(initialRows),[todos,setTodos]=useState<{text:string;done:boolean}[]>([{text:'整理今天的重点',done:false}]),[todo,setTodo]=useState(''),[panel,setPanel]=useState<'table'|'todo'>('table');
 const [restChoice,setRestChoice]=useState('');

 const ambience=useRef<RelaxAudio|null>(null),version=useRef(0),workRef=useRef(false),sceneRef=useRef<Scene>('雨窗'),volumeRef=useRef(.25),restoreTitle=useRef('歇一会儿 · 摸鱼页');
 function stopSound(){version.current++;ambience.current?.stop();setSound(false)}
 async function startSound(){stopSound();const token=version.current;try{ambience.current??=new RelaxAudio();const ok=await ambience.current.start(sceneRef.current,volumeRef.current);if(token!==version.current||workRef.current)return;if(ok){setSound(true);setNotice('声音已轻轻打开。调节环境强度，眼前的雨势、叶声和枝梢也会变化。')}}catch{stopSound();setNotice('声音播放失败，请允许浏览器播放声音后重试。')}}
 function toggleWork(){if(!workRef.current)stopSound();workRef.current=!workRef.current;setWork(workRef.current);}
 useEffect(()=>{restoreTitle.current=document.title;try{localStorage.removeItem('rest:reduce-motion');if(readLocal<string>('break-scene','雨窗')==='云海')writeLocal('break-scene','雨窗')}catch{};const s=readLocal<unknown>('break-scene','雨窗');if(['雨窗','竹林'].includes(s as string)){setScene(s as Scene);sceneRef.current=s as Scene}const t=readLocal<unknown>('break-time','18:00');if(typeof t==='string'&&/^([01]\d|2[0-3]):[0-5]\d$/.test(t)){setTarget(t);setDraft(t)}const v=readLocal<unknown>('break-volume',.25);if(typeof v==='number'&&v>=0&&v<=1){setVolume(v);volumeRef.current=v}
 const r=readLocal<unknown>('work-rows',initialRows);if(Array.isArray(r)&&r.length<=100&&r.every(x=>Array.isArray(x)&&x.length===4&&x.every(c=>typeof c==='string')))setRows(r);const ts=readLocal<unknown>('work-todos',todos);if(Array.isArray(ts)&&ts.length<=100&&ts.every(x=>x&&typeof x.text==='string'&&typeof x.done==='boolean'))setTodos(ts);setLoaded(true);setNow(new Date());
 const timer=setInterval(()=>setNow(new Date()),1000);const key=(e:KeyboardEvent)=>{const el=e.target instanceof HTMLElement ? e.target : null;if(el?.closest('input,textarea,select,[contenteditable="true"]'))return;if(e.code==='KeyB'&&!e.repeat){e.preventDefault();toggleWork();}if(e.key==='Escape'&&workRef.current){workRef.current=false;setWork(false)}};const hidden=()=>{if(document.hidden)stopSound()};window.addEventListener('keydown',key);document.addEventListener('visibilitychange',hidden);return()=>{clearInterval(timer);window.removeEventListener('keydown',key);document.removeEventListener('visibilitychange',hidden);version.current++;ambience.current?.stop();document.title=restoreTitle.current;};},[]);
 useEffect(()=>{document.title=work?'项目进度表':'歇一会儿 · 摸鱼页'},[work]);
 useEffect(()=>{const cleared=(event:Event)=>{const group=(event as CustomEvent<string>).detail;if(group==='work'){skipWorkPersist.current=true;setRows([]);setTodos([]);}if(group==='preferences'){stopSound();setScene('雨窗');sceneRef.current='雨窗';setVolume(.25);volumeRef.current=.25;setTarget('18:00');setDraft('18:00');}};window.addEventListener('rest-data-cleared',cleared);return()=>window.removeEventListener('rest-data-cleared',cleared)},[]);
 useEffect(()=>{if(skipWorkPersist.current){skipWorkPersist.current=false;return;}if(loaded){writeLocal('work-rows',rows);writeLocal('work-todos',todos)}},[rows,todos,loaded]);
 const end=now?new Date(now):null;if(end){const [h,m]=target.split(':').map(Number);end.setHours(h,m,0,0)}const remaining=end&&now?Math.max(0,end.getTime()-now.getTime()):0;const units=[Math.floor(remaining/3600000),Math.floor(remaining/60000)%60,Math.floor(remaining/1000)%60];
 function choose(s:Scene){stopSound();setScene(s);sceneRef.current=s;writeLocal('break-scene',s);}
 const motion=sceneDynamics(volume);
 const reminder=<OffworkReminder target={target} now={now} work={work}/>;
 if(work)return <><main className="work-view"><header><div><span className="sheet-logo">表</span><b>项目工作台</b><small>本地演示 · 自动保存到此浏览器</small></div><button onClick={toggleWork}>返回休息页 · 快捷键 B</button></header><div className="work-body"><aside><h2>工作空间</h2><button className={panel==='table'?'active':''} onClick={()=>setPanel('table')}>▦ 项目进度表</button><button className={panel==='todo'?'active':''} onClick={()=>setPanel('todo')}>☑ 我的待办</button><p>仅切换当前网页。<br/>不影响电脑桌面或浏览记录。</p></aside><section><div className="work-page-title"><div><small>工作空间 / {panel==='table'?'项目进度':'我的待办'}</small><h1>{panel==='table'?'项目进度表':'今天做什么'}</h1></div><span>环境声已关闭</span></div>{panel==='table'?<><div className="work-toolbar"><button disabled={rows.length>=100} onClick={()=>setRows(v=>[...v,['新任务','未开始','','']])}>＋ 添加行</button><small>直接编辑单元格 · 最多一百行 · 请勿填入敏感工作信息</small></div><div className="sheet-scroll"><table><thead><tr><th>序号</th>{['事项','状态','截止时间','备注','操作'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}><td>{i+1}</td>{row.map((cell,j)=><td key={j}><input aria-label={`第${i+1}行${['事项','状态','截止时间','备注'][j]}`} value={cell} maxLength={150} onChange={e=>setRows(v=>v.map((r,n)=>n===i?r.map((c,k)=>k===j?e.target.value:c):r))}/></td>)}<td><button onClick={()=>setRows(v=>v.filter((_,n)=>n!==i))} aria-label={`删除第${i+1}行`}>删除</button></td></tr>)}</tbody></table></div></>:<><form className="todo-form" onSubmit={e=>{e.preventDefault();if(todo.trim()&&todos.length<100){setTodos(v=>[...v,{text:todo.trim(),done:false}]);setTodo('')}}}><input value={todo} maxLength={120} onChange={e=>setTodo(e.target.value)} placeholder="添加一件小事" aria-label="新待办"/><button disabled={!todo.trim()||todos.length>=100}>添加待办</button></form><div className="todo-items">{todos.map((t,i)=><div key={i}><label><input type="checkbox" checked={t.done} onChange={()=>setTodos(v=>v.map((x,n)=>n===i?{...x,done:!x.done}:x))}/><span className={t.done?'checked':''}>{t.text}</span></label><button onClick={()=>setTodos(v=>v.filter((_,n)=>n!==i))}>删除</button></div>)}</div></>}</section></div></main>{reminder}</>;
 return <><main className="break-page care-page"><header className="break-top"><Link href="/" className="break-brand"><span>歇</span><b>歇一会儿<small>你的轻娱乐休息站</small></b></Link><nav><Link href="/">娱乐 · 玩一局</Link><Link href="/break" aria-current="page">摸鱼 · 放空一下</Link></nav><button className="work-switch" onClick={toggleWork}>▦ 一键工作视图 <kbd>B</kbd></button></header><div className="break-container"><section className="break-hero"><div><span>这段时间，留给自己</span><h1>辛苦了，<em>这会儿不用那么用力。</em></h1><p>不用立刻振作，也不用把休息变得有意义。<br/>在这里坐一会儿，想走的时候就走。</p></div><div className="break-stamp">今日宜<br/><b>歇歇</b><small>你不必一直撑着</small></div></section>
 <div className="rest-choices" aria-label="选择此刻的休息方式">{[{name:'脑袋有点吵',desc:'听听雨，吹吹风',id:'scenery'},{name:'手上想动动',desc:'捏气泡，不用计分',id:'decompress'},{name:'心里有点堵',desc:'写下来，不用想通',id:'vent'}].map(item=><button key={item.id} className={restChoice===item.id?'active':''} onClick={()=>{setRestChoice(item.id);document.getElementById(item.id)?.scrollIntoView({behavior:'smooth',block:'start'})}}><b>{item.name}</b><span>{item.desc} ↗</span></button>)}</div><div className="comfort-tools"><small>声音默认关闭。轻雨或微风，都由你慢慢调。</small></div><div className="break-grid"><section className="scene-panel" id="scenery"><div className="break-heading"><div><small>桌面小景</small><h2>给脑袋，开一扇小窗</h2></div><div className="scene-tabs">{(['雨窗','竹林']as Scene[]).map(s=><button className={scene===s?'active':''} key={s} onClick={()=>choose(s)}>{s}</button>)}</div></div><AmbientWindow scene={scene} intensity={volume}/><div className="scene-presets" aria-label="环境强度预设">{[{name:'轻柔',v:.15},{name:'适中',v:.5},{name:'充沛',v:.95}].map(p=><button key={p.name} aria-pressed={Math.abs(volume-p.v)<.02} onClick={()=>{setVolume(p.v);volumeRef.current=p.v;ambience.current?.setVolume(p.v);writeLocal('break-volume',p.v)}}>{p.name}</button>)}</div><div className="scene-audio"><button aria-pressed={sound} onClick={()=>sound?stopSound():void startSound()}>{sound?'关闭环境声':'开启环境声'}</button><label>环境强度 <input type="range" aria-label="环境强度" min="0" max="1" step=".05" value={volume} onChange={e=>{const v=Number(e.target.value);setVolume(v);volumeRef.current=v;ambience.current?.setVolume(v);writeLocal('break-volume',v)}}/></label><small>{scene==='雨窗'?`由疏到密的雨幕 · ${motion.label}`:`根部稳定、上梢随风弯曲 · ${motion.label}`} · 画面与声音同时变化</small></div><p className="sound-notice" role="status">{notice||'程序合成雨声与风声，非实地录音。强度越高，雨越密、风越明显；声音仍需手动开启，切到后台或工作视图自动静音。'}</p></section>

 <Decompress />
 
 <VentStation /> <section className="countdown-panel"><small>今天的盼头</small><h2>距离收工，还有</h2><div className="time-units">{units.map((v,i)=><span key={i}><b>{String(v).padStart(2,'0')}</b><small>{['小时','分钟','秒'][i]}</small></span>)}</div><p role="status">{!now?'正在读取本地时间…':remaining===0?'今天设定的时间已到，辛苦啦。':'不是每一分钟都要有产出，慢一点也没关系。'}</p><form onSubmit={e=>{e.preventDefault();if(draft){setTarget(draft);writeLocal('break-time',draft)}}}><label>今天几点收工？<input type="time" aria-label="今天下班时间" required value={draft} onChange={e=>setDraft(e.target.value)}/></label><button>设定时间</button></form><small className="countdown-note">按设备本地时间计算；超过今天的目标时间后归零并在页面内弹出提醒；同一天同一时间只提醒一次。页面关闭无法提醒，后台可能延迟，返回后补提醒。</small></section><section className="break-help"><span>给自己一个缓冲</span><h2>随时切换，不必慌张。</h2><p>老板过来了？赶紧切换。按一下 B，先回工作视图；随时切换，不必慌张。</p><p>按 <kbd>B</kbd>，当前页面会切换成可编辑的项目表格。按 <kbd>B</kbd> 或 <kbd>Esc</kbd> 返回；正在输入文字时不触发快捷键。</p><button onClick={toggleWork}>打开工作视图 →</button><small>这是网页内的演示工作台，不会替换操作系统桌面，不会清除浏览记录。</small></section></div><LocalDataPanel /><footer className="break-footer"><span>歇一会儿 · 不催你</span><span>偏好仅保存在当前浏览器 · 不登录 · 不跨设备同步</span><Link href="/">想玩一局？去娱乐页 →</Link></footer></div></main>{reminder}</>
}
