"use client";
import Link from 'next/link';
import { useEffect, useRef, useState } from 'react';
import { readLocal, writeLocal } from '@/lib/local-preferences';
import { useInferenceRun } from '@/lib/use-inference-run';
import './break.css';
import Decompress from '@/components/decompress';
import OffworkReminder from '@/components/offwork-reminder';
import { RelaxAudio } from '@/lib/relax-audio';
type Scene='雨窗'|'竹林'|'云海';
const initialRows=[['需求整理','待确认','周一','补充使用场景'],['页面评审','进行中','周三','核对交互细节'],['联调检查','未开始','周五','记录问题清单'],['周报归档','未开始','周五','整理本周进展']];
export default function BreakPage(){
 const [work,setWork]=useState(false),[scene,setScene]=useState<Scene>('雨窗'),[sound,setSound]=useState(false),[volume,setVolume]=useState(.25),[notice,setNotice]=useState(''),[loaded,setLoaded]=useState(false);
 const [popped,setPopped]=useState<number[]>([]),[target,setTarget]=useState('18:00'),[draft,setDraft]=useState('18:00'),[now,setNow]=useState<Date|null>(null),[rows,setRows]=useState(initialRows),[todos,setTodos]=useState<{text:string;done:boolean}[]>([{text:'整理今天的重点',done:false}]),[todo,setTodo]=useState(''),[panel,setPanel]=useState<'table'|'todo'>('table');
 const [vent,setVent]=useState(''),[ventMode,setVentMode]=useState<'倒掉'|'吐槽'|'缓一缓'>('倒掉'),[ventResult,setVentResult]=useState<{title:string;text:string;tag:string;local?:boolean}|null>(null),[ventNotice,setVentNotice]=useState('');const ventInput=useRef<HTMLTextAreaElement>(null);const {loading:ventLoading,run:runVent}=useInferenceRun();
 const ambience=useRef<RelaxAudio|null>(null),version=useRef(0),workRef=useRef(false),sceneRef=useRef<Scene>('雨窗'),volumeRef=useRef(.25),restoreTitle=useRef('歇一会儿 · 摸鱼页');
 function stopSound(){version.current++;ambience.current?.stop();setSound(false)}
 async function startSound(){stopSound();const token=version.current;try{ambience.current??=new RelaxAudio();const ok=await ambience.current.start(sceneRef.current,volumeRef.current);if(token!==version.current||workRef.current)return;if(ok){setSound(true);setNotice('分层合成环境声已开启：雨底与近处雨滴 / 风与竹叶 / 缓慢山风。')}}catch{stopSound();setNotice('声音播放失败，请允许浏览器播放声音后重试。')}}
 function toggleWork(){if(!workRef.current)stopSound();workRef.current=!workRef.current;setWork(workRef.current);}
 useEffect(()=>{restoreTitle.current=document.title;const s=readLocal<unknown>('break-scene','雨窗');if(['雨窗','竹林','云海'].includes(s as string)){setScene(s as Scene);sceneRef.current=s as Scene}const t=readLocal<unknown>('break-time','18:00');if(typeof t==='string'&&/^([01]\d|2[0-3]):[0-5]\d$/.test(t)){setTarget(t);setDraft(t)}const v=readLocal<unknown>('break-volume',.25);if(typeof v==='number'&&v>=0&&v<=1){setVolume(v);volumeRef.current=v}
 const r=readLocal<unknown>('work-rows',initialRows);if(Array.isArray(r)&&r.length<=100&&r.every(x=>Array.isArray(x)&&x.length===4&&x.every(c=>typeof c==='string')))setRows(r);const ts=readLocal<unknown>('work-todos',todos);if(Array.isArray(ts)&&ts.length<=100&&ts.every(x=>x&&typeof x.text==='string'&&typeof x.done==='boolean'))setTodos(ts);setLoaded(true);setNow(new Date());
 const timer=setInterval(()=>setNow(new Date()),1000);const key=(e:KeyboardEvent)=>{const el=e.target instanceof HTMLElement ? e.target : null;if(el?.closest('input,textarea,select,[contenteditable="true"]'))return;if(e.code==='KeyB'&&!e.repeat){e.preventDefault();toggleWork();}if(e.key==='Escape'&&workRef.current){workRef.current=false;setWork(false)}};const hidden=()=>{if(document.hidden)stopSound()};window.addEventListener('keydown',key);document.addEventListener('visibilitychange',hidden);return()=>{clearInterval(timer);window.removeEventListener('keydown',key);document.removeEventListener('visibilitychange',hidden);version.current++;ambience.current?.stop();document.title=restoreTitle.current;};},[]);
 useEffect(()=>{document.title=work?'项目进度表':'歇一会儿 · 摸鱼页'},[work]);
 useEffect(()=>{if(loaded){writeLocal('work-rows',rows);writeLocal('work-todos',todos)}},[rows,todos,loaded]);
 const end=now?new Date(now):null;if(end){const [h,m]=target.split(':').map(Number);end.setHours(h,m,0,0)}const remaining=end&&now?Math.max(0,end.getTime()-now.getTime()):0;const units=[Math.floor(remaining/3600000),Math.floor(remaining/60000)%60,Math.floor(remaining/1000)%60];
 async function processVent(){if(!vent.trim()||ventLoading)return;setVentNotice('');try{const task=await runVent('anthropic/claude-haiku-4-5',{text:`烦恼：${vent}\n处理方式：${ventMode}`,system_prompt:'你是一个温和的情绪整理助手。只输出 JSON，不要 markdown：{"title":"不超过8字的回收标签","text":"一句不超过30字的温柔回应或吐槽","tag":"已倒掉|已吐槽|先缓一缓"}。不诊断、不说教、不提供医疗建议、不攻击他人；不要复述隐私。'});const raw=(task.output as {response?:string}|null)?.response||'';const clean=raw.replace(/```(?:json)?/g,'').trim(),start=clean.indexOf('{'),end=clean.lastIndexOf('}');if(start<0||end<=start)throw new Error('无结果');setVentResult({...JSON.parse(clean.slice(start,end+1)),local:false});}catch{const map={倒掉:{title:'今日烦恼，已倒掉',text:'这件事先放下，今天的你不必继续替它耗电。',tag:'已倒掉'},吐槽:{title:'吐槽已寄出',text:'你已经很努力了，先把这口气还给自己。',tag:'已吐槽'},缓一缓:{title:'先不急着解决',text:'事情可以明天再想，现在先给自己五分钟。',tag:'先缓一缓'}} as const;setVentResult({...map[ventMode],local:true});setVentNotice('生成服务暂时不可用，以下为预设缓冲文案，并非根据输入生成。请求已尝试发送，不能保证第三方不留存。');}}
 const clearVent=()=>{setVent('');setVentResult(null);setVentNotice('');ventInput.current?.focus()};
 function choose(s:Scene){stopSound();setScene(s);sceneRef.current=s;writeLocal('break-scene',s);}
 const reminder=<OffworkReminder target={target} now={now} work={work}/>;
 if(work)return <><main className="work-view"><header><div><span className="sheet-logo">表</span><b>项目工作台</b><small>本地演示 · 自动保存到此浏览器</small></div><button onClick={toggleWork}>返回休息页 · 快捷键 B</button></header><div className="work-body"><aside><h2>工作空间</h2><button className={panel==='table'?'active':''} onClick={()=>setPanel('table')}>▦ 项目进度表</button><button className={panel==='todo'?'active':''} onClick={()=>setPanel('todo')}>☑ 我的待办</button><p>仅切换当前网页。<br/>不影响电脑桌面或浏览记录。</p></aside><section><div className="work-page-title"><div><small>工作空间 / {panel==='table'?'项目进度':'我的待办'}</small><h1>{panel==='table'?'项目进度表':'今天做什么'}</h1></div><span>环境声已关闭</span></div>{panel==='table'?<><div className="work-toolbar"><button disabled={rows.length>=100} onClick={()=>setRows(v=>[...v,['新任务','未开始','','']])}>＋ 添加行</button><small>直接编辑单元格 · 最多一百行 · 请勿填入敏感工作信息</small></div><div className="sheet-scroll"><table><thead><tr><th>序号</th>{['事项','状态','截止时间','备注','操作'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}><td>{i+1}</td>{row.map((cell,j)=><td key={j}><input aria-label={`第${i+1}行${['事项','状态','截止时间','备注'][j]}`} value={cell} maxLength={150} onChange={e=>setRows(v=>v.map((r,n)=>n===i?r.map((c,k)=>k===j?e.target.value:c):r))}/></td>)}<td><button onClick={()=>setRows(v=>v.filter((_,n)=>n!==i))} aria-label={`删除第${i+1}行`}>删除</button></td></tr>)}</tbody></table></div></>:<><form className="todo-form" onSubmit={e=>{e.preventDefault();if(todo.trim()&&todos.length<100){setTodos(v=>[...v,{text:todo.trim(),done:false}]);setTodo('')}}}><input value={todo} maxLength={120} onChange={e=>setTodo(e.target.value)} placeholder="添加一件小事" aria-label="新待办"/><button disabled={!todo.trim()||todos.length>=100}>添加待办</button></form><div className="todo-items">{todos.map((t,i)=><div key={i}><label><input type="checkbox" checked={t.done} onChange={()=>setTodos(v=>v.map((x,n)=>n===i?{...x,done:!x.done}:x))}/><span className={t.done?'checked':''}>{t.text}</span></label><button onClick={()=>setTodos(v=>v.filter((_,n)=>n!==i))}>删除</button></div>)}</div></>}</section></div></main>{reminder}</>;
 return <><main className="break-page"><header className="break-top"><Link href="/" className="break-brand"><span>歇</span><b>歇一会儿<small>你的轻娱乐休息站</small></b></Link><nav><Link href="/">娱乐 · 玩一局</Link><Link href="/break" aria-current="page">摸鱼 · 放空一下</Link></nav><button className="work-switch" onClick={toggleWork}>▦ 一键工作视图 <kbd>B</kbd></button></header><div className="break-container"><section className="break-hero"><div><span>这段时间，留给自己</span><h1>不必通关，<em>也可以很开心。</em></h1><p>听一场雨，捏几个泡泡，等一等下班。<br/>先把脑袋里的忙碌，轻轻放一边。</p></div><div className="break-stamp">今日宜<br/><b>松弛</b><small>什么都不赶</small></div></section>
 <div className="break-grid"><section className="scene-panel"><div className="break-heading"><div><small>桌面小景</small><h2>把窗口，换个风景</h2></div><div className="scene-tabs">{(['雨窗','竹林','云海']as Scene[]).map(s=><button className={scene===s?'active':''} key={s} onClick={()=>choose(s)}>{s}</button>)}</div></div><div className={`scene-stage scene-${scene}`} aria-label={`${scene}动态小景`}><div className="scene-sun"/><div className="scene-mountain m-a"/><div className="scene-mountain m-b"/>{scene==='雨窗'&&<div className="rain-window">{Array.from({length:35},(_,i)=><i key={i} style={{left:`${(i*37)%100}%`,animationDelay:`${i*.17}s`,animationDuration:`${1.1+(i%5)*.2}s`}}/>)}<b/></div>}{scene==='竹林'&&<div className="bamboos">{Array.from({length:9},(_,i)=><i key={i} style={{left:`${i*12}%`,height:`${70+(i%3)*13}%`,animationDelay:`${i*.3}s`}}><b/><b/><b/></i>)}</div>}{scene==='云海'&&<div className="cloud-sea"><i/><i/><i/></div>}<div className="scene-caption">{scene==='雨窗'?'雨会停，事情也会慢慢过去。':scene==='竹林'?'风穿过竹叶，不需要回答。':'没有待办的云，正在路过。'}</div></div><div className="scene-audio"><button aria-pressed={sound} onClick={()=>sound?stopSound():void startSound()}>{sound?'关闭环境声':'开启环境声'}</button><label>音量 <input type="range" min="0" max="1" step=".05" value={volume} onChange={e=>{const v=Number(e.target.value);setVolume(v);volumeRef.current=v;ambience.current?.setVolume(v);writeLocal('break-volume',v)}}/></label><small>分层合成环境声 · 非实地录音</small></div><p className="sound-notice" role="status">{notice||'声音只在你主动开启后播放；切到后台或工作视图会自动关闭。'}</p></section>
 <section className="countdown-panel"><small>今天的盼头</small><h2>距离收工，还有</h2><div className="time-units">{units.map((v,i)=><span key={i}><b>{String(v).padStart(2,'0')}</b><small>{['小时','分钟','秒'][i]}</small></span>)}</div><p role="status">{!now?'正在读取本地时间…':remaining===0?'今天设定的时间已到，辛苦啦。':'做完手头这一点，就离自由更近一点。'}</p><form onSubmit={e=>{e.preventDefault();if(draft){setTarget(draft);writeLocal('break-time',draft)}}}><label>今天几点收工？<input type="time" aria-label="今天下班时间" required value={draft} onChange={e=>setDraft(e.target.value)}/></label><button>设定时间</button></form><small className="countdown-note">按设备本地时间计算；超过今天的目标时间后归零并在页面内弹出提醒；同一天同一时间只提醒一次。页面关闭无法提醒，后台可能延迟，返回后补提醒。</small></section>
 <Decompress />
 <section className="break-help"><span>给自己一个缓冲</span><h2>歇够了，再认真。</h2><p>老板过来了？赶紧切换。按一下 B，先回工作视图；歇够了，再认真。</p><p>按 <kbd>B</kbd>，当前页面会切换成可编辑的项目表格。按 <kbd>B</kbd> 或 <kbd>Esc</kbd> 返回；正在输入文字时不触发快捷键。</p><button onClick={toggleWork}>打开工作视图 →</button><small>这是网页内的演示工作台，不会替换操作系统桌面，不会清除浏览记录。</small></section>
 <section className="vent-panel"><div className="break-heading"><div><small>烦恼回收站 · 不公开</small><h2>把心里的不痛快，先放这里</h2></div><span>使用在线文本生成服务</span></div><p className="vent-intro">不评论、不围观。点击处理后，输入会发送给第三方文本生成服务；服务可能留存请求，请勿填写敏感信息。清空仅移除当前页面内容，不撤回已发送请求。</p><textarea ref={ventInput} className="vent-input" value={vent} maxLength={240} onChange={e=>{setVent(e.target.value);setVentResult(null);setVentNotice('')}} placeholder="例如：今天开了三个会，最后什么也没决定。"/><div className="vent-meta"><span>{vent.length}/240 · 请不要填写姓名、公司机密或隐私</span><button onClick={clearVent}>清空</button></div><div className="vent-modes">{(['倒掉','吐槽','缓一缓'] as const).map(m=><button key={m} className={ventMode===m?'active':''} onClick={()=>setVentMode(m)}>{m}</button>)}<button className="vent-submit" disabled={!vent.trim()||ventLoading} onClick={processVent}>{ventLoading?'整理中…':'处理一下 →'}</button></div>{ventResult&&<div className="vent-receipt"><span>{ventResult.local?'本地缓冲版':'回收凭条'}</span><b>{ventResult.title}</b><p>{ventResult.text}</p><small>「{ventResult.tag}」 · 本站不设公开内容墙</small></div>}{ventNotice&&<p className="vent-notice" role="status">{ventNotice}</p>}</section></div><footer className="break-footer"><span>歇一会儿 · 不催你</span><span>偏好仅保存在当前浏览器 · 不登录 · 不跨设备同步</span><Link href="/">想玩一局？去娱乐页 →</Link></footer></div></main>{reminder}</>
}
